# Generated by Django 6.0.4 on 2026-05-10 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_schema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentversion',
            options={'ordering': ['version_number']},
        ),
    ]
